<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_platform_login.proto

namespace GPBMetadata\Platform;

class ApiPlatformLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0020a21706c6174666f726d2f6170695f706c6174666f726d5f6c6f67" .
            "696e2e70726f746f1208706c6174666f726d225c0a17417069506c617466" .
            "6f726d4c6f67696e5265717565737412180a1070686f6e65436f756e7472" .
            "79436f646518012001280912130a0b70686f6e654e756d62657218022001" .
            "280912120a0a766572696679436f6465180320012809224a0a1841706950" .
            "6c6174666f726d4c6f67696e526573706f6e7365122e0a0d6c6f67696e55" .
            "7365725479706518012001280e32172e706c6174666f726d2e4c6f67696e" .
            "55736572547970652a4e0a0d4c6f67696e557365725479706512130a0f55" .
            "73657254797065496e76616c6964100012130a0f55736572547970655265" .
            "7369746572100112130a0f55736572547970654c6f67696e65721002422f" .
            "0a17636f6d2e7a616c792e70726f746f2e706c6174666f726dca02135a61" .
            "6c795c50726f746f5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

