<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_create.proto

namespace GPBMetadata\Site;

class ApiGroupCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4010a1b736974652f6170695f67726f75705f6372656174652e70726f" .
            "746f120473697465222a0a1541706947726f757043726561746552657175" .
            "65737412110a0967726f75704e616d6518012001280922400a1641706947" .
            "726f7570437265617465526573706f6e736512260a0770726f66696c6518" .
            "012001280b32152e636f72652e416c6c47726f757050726f66696c654259" .
            "0a13636f6d2e7a616c792e70726f746f2e736974655a306769746875622e" .
            "636f6d2f616b6178696e636f6d2f6475636b636861742d67617465776179" .
            "2f70726f746f2f73697465ca020f5a616c795c50726f746f5c5369746562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

