<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_reg.proto

namespace GPBMetadata\Site;

class ApiPassportPasswordReg
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac3020a24736974652f6170695f70617373706f72745f70617373776f72" .
            "645f7265672e70726f746f120473697465227a0a1d41706950617373706f" .
            "727450617373776f72645265675265717565737412110a096c6f67696e4e" .
            "616d6518012001280912100a0870617373776f7264180220012809120d0a" .
            "05656d61696c18032001280912100a086e69636b6e616d65180420012809" .
            "12130a0b736974655075626b50656d18052001280922360a1e4170695061" .
            "7373706f727450617373776f7264526567526573706f6e736512140a0c70" .
            "726553657373696f6e496418012001280942590a13636f6d2e7a616c792e" .
            "70726f746f2e736974655a306769746875622e636f6d2f616b6178696e63" .
            "6f6d2f6475636b636861742d676174657761792f70726f746f2f73697465" .
            "ca020f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

