<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_plugin_proxy.proto

namespace GPBMetadata\Site;

class ApiPluginProxy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Net::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9020a1b736974652f6170695f706c7567696e5f70726f78792e70726f" .
            "746f12047369746522790a15417069506c7567696e50726f787952657175" .
            "65737412100a08706c7567696e4964180120012805120b0a0375726c1802" .
            "2001280912230a066d6574686f6418032001280e32132e636f72652e4874" .
            "7470517565727954797065120c0a04626f6479180420012809120e0a0663" .
            "6f6f6b696518052001280922360a16417069506c7567696e50726f787952" .
            "6573706f6e7365120c0a04626f6479180120012809120e0a06636f6f6b69" .
            "6518022001280942590a13636f6d2e7a616c792e70726f746f2e73697465" .
            "5a306769746875622e636f6d2f616b6178696e636f6d2f6475636b636861" .
            "742d676174657761792f70726f746f2f73697465ca020f5a616c795c5072" .
            "6f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

