<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_sync.proto

namespace GPBMetadata\Site;

class ImCtsSync
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a16736974652f696d5f6374735f73796e632e70726f746f120473" .
            "697465224e0a10496d43747353796e6352657175657374120f0a07753243" .
            "6f756e7418012001280512120a0a67726f7570436f756e74180220012805" .
            "12150a0d757064617465506f696e74657218032001280842590a13636f6d" .
            "2e7a616c792e70726f746f2e736974655a306769746875622e636f6d2f61" .
            "6b6178696e636f6d2f6475636b636861742d676174657761792f70726f74" .
            "6f2f73697465ca020f5a616c795c50726f746f5c53697465620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

