<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_plugin_proxy.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiPluginProxyResponse</code>
 */
class ApiPluginProxyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string body = 1;</code>
     */
    private $body = '';
    /**
     * Generated from protobuf field <code>string cookie = 2;</code>
     */
    private $cookie = '';

    public function __construct() {
        \GPBMetadata\Site\ApiPluginProxy::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string body = 1;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cookie = 2;</code>
     * @return string
     */
    public function getCookie()
    {
        return $this->cookie;
    }

    /**
     * Generated from protobuf field <code>string cookie = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCookie($var)
    {
        GPBUtil::checkString($var, True);
        $this->cookie = $var;

        return $this;
    }

}

