<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_auth.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>platform.ApiPushAuthResponse</code>
 */
class ApiPushAuthResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Platform\ApiPushAuth::initOnce();
        parent::__construct();
    }

}

