<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_platform_login.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: platform.api.platform.login
 * error:
 *    error.phone  the phone number format is invalid.
 *
 * Generated from protobuf message <code>platform.ApiPlatformLoginRequest</code>
 */
class ApiPlatformLoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     */
    private $phoneCountryCode = '';
    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     */
    private $phoneNumber = '';
    /**
     * Generated from protobuf field <code>string verifyCode = 3;</code>
     */
    private $verifyCode = '';

    public function __construct() {
        \GPBMetadata\Platform\ApiPlatformLogin::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     * @return string
     */
    public function getPhoneCountryCode()
    {
        return $this->phoneCountryCode;
    }

    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->phoneCountryCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string verifyCode = 3;</code>
     * @return string
     */
    public function getVerifyCode()
    {
        return $this->verifyCode;
    }

    /**
     * Generated from protobuf field <code>string verifyCode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVerifyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->verifyCode = $var;

        return $this;
    }

}

